export const commands = {
  help: [
    " Available commands:",
    " about      - who I am",
    " skills     - technical skills",
    " projects   - things I built",
    " contact    - how to reach me",
    " cv         - download my CV",
    " clear      - clear the terminal"
  ],
cv: [
    "📄 Downloading Jan's CV...",
    "If the download doesn't start automatically, click this link:",
    "/Jan_Joshua_Bongo_CV.pdf"
  ],
about: [
  "╔══════════════════════════════════════════════════════════╗",
  "║                    JAN JOSHUA - PROFILE                  ║",
  "╚══════════════════════════════════════════════════════════╝",
  "",
  "  ▸ IT Professional with expertise in backend development,",
  "    systems architecture, and real-time applications.",
  "",
  "  ▸ Technical Skills:",
  "    • Languages: JavaScript (Node.js, React), Java, Python, C#",
  "    • Backend: REST APIs, WebSocket, Socket.IO, SignalR",
  "    • Frontend: React, Vite, TailwindCSS, React Native",
  "    • Databases: MySQL, MongoDB, MariaDB, SQLite, SQL Server",
  "    • Infrastructure: Linux (Ubuntu), VPS, Apache, Nginx,",
  "      SSL/TLS, reverse proxy, firewall, shell scripting",
  "    • IoT & Networking: RTSP, MQTT, IP cameras, CCTV systems",
  "    • Digital Forensics: Autopsy, Wireshark, data recovery",
  "",
  "  ▸ Project Highlights:",
  "    • Terminal Portfolio: Interactive command-line portfolio",
  "      (React, Vite, TailwindCSS)",
  "    • Document and Task monitoring System",
  "    • Mobile Chat App: Node.js, React Native, WebRTC, WebSocket,",
  "      MySQL/MariaDB",
  "    • Remote Desktop App: Java, MySQL, SSL/TLS",
  "    • Screen Monitoring Tool: .NET Core, SignalR, C#, SQL Server",
  "",
  "",
  "  ▸ Core Competencies:",
  "    • Real‑time system design & implementation",
  "    • Server setup, hardening, and optimization",
  "    • Database design and performance tuning",
  "    • Secure coding and encryption (SSL/TLS)",
  "    • Cross‑platform development",
  "",
  "  ▸ Based: Philippines",
  "  ▸ Contact: janjoshua1110@gmail.com",
  "",
  "  ▸ Open to collaboration and freelance opportunities."
],

  skills: [
    " Programming:",
    "   - JavaScript (Node.js, React, Vite)",
    "   - Java, Python",
    "",
    " Web & Backend:",
    "   - REST APIs",
    "   - Socket.IO",
    "   - MySQL",
    "",
    " Server & Infrastructure:",
    "   - VPS administration",
    "   - Apache, SSL/TLS",
    "   - Reverse proxy & optimization",
    "   - SSH key access control",
    "",
    " Linux Administration:",
    "   - SSH",
    "   - Firewall configuration",
    "   - Shell scripting & backups",
    "",
    " IoT & Networking:",
    "   - CCTV systems",
    "   - RTSP, HTTP, MQTT",
    "   - Synology (NAS) Server Setup",
    "",
    " Digital Forensics:",
    "   - Autopsy",
    "   - Wireshark",
    "   - Magnet Axiom",
    "   - Data recovery & investigation"
  ],

  projects: [
    "📁 Available Projects:",
    "",
    "  [1] This Portfolio",
    "    └─ React, Vite, TailwindCSS",
    "",
    "  [2] Document and Task monitoring System",
    "    └─ Node.js, MySQL, React, Vite, TailwindCSS",
    "",
    "  [3] Mobile Chat App",
    "    └─ Node.js, React Native, WebRTC, WebSocket, MySQL/MariaDB",
    "",
    "  [4] Remote Desktop App",
    "    └─ Java, MySQL, Socket Programming, SSL/TLS",
    "",
    "  [5] Remote screen monitoring App",
    "    └─ .NET Core, C#, SignalR, WebSocket, SQL Server",
    "",
    "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    "",
    "📌 Click any [number] above or type:",
    "  project 1    - View Portfolio details",
    "  project 2    - View Document System",
    "  project 3    - View Chat App",
    "  project 4    - View Remote Desktop",
    "  project 5    - View Screen Monitor"
  ],

  contact: [
    " Email: janjoshua1110@gmail.com",
    " Address: Fortune, Marikina, 1812",
    " Contact No.: +639171056495"
  ]
};